
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:/Users/zhoujian/Workspace/self/paper/spring-cloud-study/db/db;DATABASE_TO_UPPER=FALSE
    username: root
    password:
  #在浏览器中开启控制台
  h2.console.enabled: true
  #jpa,注意数据库改成h2
  jpa:
    open-in-view: false
    database: h2
    show-sql: true
    hibernate.ddl-auto: update
