
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

dubbo:
  cloud:
    subscribed-services: spring-cloud-serviceb-dubbo
  registry:
    address: spring-cloud://localhost       # 挂载到 Spring Cloud 注册中心
  scan:
    base-packages: priv.zujool.springcloudstudy.service   #指定 Dubbo 服务实现类的扫描基准包
  protocols:
    dubbo:
      name: dubbo   # Dubbo 的协议名称
      port: -1      # port 为协议端口（ -1 表示自增端口，从 20880 开始）
